title: "Seyed Mohammadreza Mousavi"
email: your.email@example.com
description: >-
  Academic homepage of Seyed Mohammadreza Mousavi – Researcher in Computer Vision.
theme: minima
markdown: kramdown
